"""empty message

Revision ID: 3d48b7151045
Revises: 
Create Date: 2023-06-12 15:11:55.545987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d48b7151045'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(), nullable=False),
    sa.Column('forma_pago', sa.Enum('EFECTIVO', 'TARJETA', name='formapago'), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('folio_factura', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    # ### end Alembic commands ###
